functionsDirectory = "C:\\Users\\OWNER\\Desktop\\therapheye\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\OWNER\\Desktop\\therapheye\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\OWNER\\Desktop\\therapheye\\netlify\\functions"

[build.environment]
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
port = 8888.0

[functions]

[functions.claude-proxy]
timeout = 26.0

[functions.push-cron]
schedule = "0 20 * * *"

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]